
x-team: &team
  build: ./vm
  privileged: true
  restart: unless-stopped

x-wireguard: &wire
  build: ./wireguard
  privileged: true
  cap_add:
    - NET_ADMIN
  sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
  restart: unless-stopped

x-wireguard-env: &wire-env
  PUID: 1000
  PGID: 1000
  TZ: Etc/UTC
  PEERS: 10
  PEERDNS: auto
  ALLOWEDIPS: 10.0.0.0/8
  SERVERURL: 172.31.207.108


services:


  router:
    build: ./router
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.tcp_timestamps=0
    restart: unless-stopped
    networks:
      players1:
        ipv4_address: 10.80.1.200
      players2:
        ipv4_address: 10.80.2.200
      players3:
        ipv4_address: 10.80.3.200
      vms:
        ipv4_address: 10.60.200.200
      game_server:
        ipv4_address: 10.10.0.200


  game_server:
    build: ./game_server
    cap_add:
      - NET_ADMIN
    volumes:
     - game-server:/app/
    restart: always
    ports:
      - 80:80
    networks:
      #scoreboard:
      game_server:
        ipv4_address: 10.10.0.1


  team0:
    <<: *team
    volumes:
      - team0-root:/root/
    networks:
      vms:
        ipv4_address: 10.60.0.1

  team1:
    <<: *team
    volumes:
      - team1-root:/root/
    networks:
      vms:
        ipv4_address: 10.60.1.1

  team2:
    <<: *team
    volumes:
      - team2-root:/root/
    networks:
      vms:
        ipv4_address: 10.60.2.1

  team3:
    <<: *team
    volumes:
      - team3-root:/root/
    networks:
      vms:
        ipv4_address: 10.60.3.1


  wireguard1:
    <<: *wire
    environment:
      <<: *wire-env
      SERVERPORT: 51820
      INTERNAL_SUBNET: 10.80.1.0/25
    ports:
      - 51820:51820/udp
    volumes:
      - ./wireguard/conf1/:/config
    networks:
      players1:
        ipv4_address: 10.80.1.128
  
  wireguard2:
    <<: *wire
    environment:
      <<: *wire-env
      INTERNAL_SUBNET: 10.80.2.0/25
      SERVERPORT: 51821
    ports:
      - 51821:51820/udp
    volumes:
      - ./wireguard/conf2/:/config
    networks:
      players2:
        ipv4_address: 10.80.2.128
  
  wireguard3:
    <<: *wire
    environment:
      <<: *wire-env
      INTERNAL_SUBNET: 10.80.3.0/25
      SERVERPORT: 51822
    ports:
      - 51822:51820/udp
    volumes:
      - ./wireguard/conf3/:/config
    networks:
      players3:
        ipv4_address: 10.80.3.128



volumes:

  game-server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./game_server/

  team0-root:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./vm-volumes/team0-root/

  team1-root:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./vm-volumes/team1-root/

  team2-root:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./vm-volumes/team2-root/

  team3-root:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./vm-volumes/team3-root/



networks:

  scoreboard:
    driver: bridge

  game_server:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.254

  vms:
    ipam:
      driver: default
      config:
        - subnet: 10.60.0.0/16
          gateway: 10.60.0.254

  players1:
    ipam:
      driver: default
      config:
        - subnet: 10.80.1.0/24
          gateway: 10.80.1.254

  players2:
    ipam:
      driver: default
      config:
        - subnet: 10.80.2.0/24
          gateway: 10.80.2.254

  players3:
    ipam:
      driver: default
      config:
        - subnet: 10.80.3.0/24
          gateway: 10.80.3.254

