version: '2.2'
services:
  sesame:
    build: .
    restart: "always"
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    ports:
      - "4280:4280"
    volumes:
      - "./volumes/service/:/app/data/"
