log_level: "debug"

round_len: 15000 # 120000 == 2 minutes (in milliseconds)
token: "1111"

nop: "10.60.0.1"
teams:
  10.60.0.1: "aaaa" # "61be55a8e2f6b4e172338bddf184d6db" # sha256(b"aaaa").digest().hex()[:32]
  10.60.1.1: "bbbb" # "81cc5b17018674b401b42f35ba07bb79" # sha256(b"bbbb").digest().hex()[:32]
  10.60.2.1: "cccc" # "b6fbd675f98e2abd22d4ed29fdc83150" # sha256(b"cccc").digest().hex()[:32]
  10.60.3.1: "dddd" # "5bf8aa57fc5a6bc547decf1cc6db63f1" # sha256(b"dddd").digest().hex()[:32]

services:
  - Notes
  - Polls

checker_dir: "../checkers/"
